theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "default"

plugins=(jekyll-include-cache)

main:
  - title: "Bio"
    url: /index.md
  - title: "CV"
    url: /CV.md
  - title: "Presentations"
    url: /Presentations.md
  - title: "Publications"
    url: /Publications.md
  - title: "Teaching"
    url: /Teaching.md
