theme: mmistakes/minimal-mistakes@4.24.0

minimal_mistakes_skin: "default"

main:
  - title: "Bio"
    url: /Index.md
  - title: "CV"
    url: /CV.md
  - title: "Presentations"
    url: /Presentations.md
  - title: "Publications"
    url: /Publications.md
  - title: "Teaching"
    url: /Teaching.md
