remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "default"

plugins: ["jekyll-include-cache"]

title: Paul Lendway

atom_feed:  
  hide: true

google_site_verification: C8Um20-6MdtkcSlOpJAMTORJyUaPrKQsnPuxmnDJDFk 

